format = """
╭─ $os$container$username$hostname$directory$git_branch$git_status$all$cmd_duration$gcloud
╰─$character"""

[line_break]
disabled = true

[os]
disabled = false
format = "[$symbol]($style) "
style = "bold white"

[os.symbols]
Debian = ""
Fedora = ""
Android = ""
Ubuntu = ""
Linux = ""

[container]
disabled = false
format = "[$symbol] "
symbol = "📦"

[username]
disabled = false
show_always = true
format = "[$user]($style)"
style_user = "bold 208"
style_root = "bold purple"

[hostname]
disabled = false
ssh_only = false
ssh_symbol = "󰒋 "
format = "[@](bold white)[$ssh_symbol$hostname]($style)[:](bold white)"
style = "bold white"

[directory]
style = "bold cyan"
format = "[$path]($style)[$read_only]($read_only_style) "
read_only = " "
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = " "
style = "bold purple"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold red"
format = '([\[$all_status$ahead_behind\]]($style) )'

[cmd_duration]
min_time = 2000
format = "took [$duration]($style) "
style = "bold yellow"

[gcloud]
disabled = false
format = "\n│ 🔗 [$symbol$account]($style) "
style = "bold cyan"
symbol = "󱇶 "

[character]
success_symbol = "[❯](bold 46)"
error_symbol = "[❯](bold 196)"
